all:
	ocamlbuild -use-ocamlfind -package qcheck e8.native

native:
	ocamlbuild -use-ocamlfind -package qcheck e8.native

byte:
	ocamlbuild -use-ocamlfind -package qcheck e8.byte

clean:
	ocamlbuild -clean
