all: 
      ocamlbuild -use-ocamlfind -package qcheck e3.native
native: 
      ocamlbuild -use-ocamlfind -package qcheck e3.native
byte: 
      ocamlbuild -use-ocamlfind -package qcheck e3.byte
clean: 
      ocamlbuild -clean
