all:
	ocamlbuild -use-ocamlfind -package qcheck e5.native

native:
	ocamlbuild -use-ocamlfind -package qcheck e5.native

byte:
	ocamlbuild -use-ocamlfind -package qcheck e5.byte

clean:
	ocamlbuild -clean
