all: 
      ocamlbuild -use-ocamlfind -package qcheck e4.native
native: 
      ocamlbuild -use-ocamlfind -package qcheck e4.native
byte: 
      ocamlbuild -use-ocamlfind -package qcheck e4.byte
clean: 
      ocamlbuild -clean
