all:
	ocamlbuild -use-ocamlfind -package qcheck e7.native

native:
	ocamlbuild -use-ocamlfind -package qcheck e7.native

byte:
	ocamlbuild -use-ocamlfind -package qcheck e7.byte

clean:
	ocamlbuild -clean
