all: 
      ocamlbuild -use-ocamlfind -package qcheck e6.native
native: 
      ocamlbuild -use-ocamlfind -package qcheck e6.native
byte: 
      ocamlbuild -use-ocamlfind -package qcheck e6.byte
clean: 
      ocamlbuild -clean
