all: 
      ocamlbuild -use-ocamlfind -package qcheck e2.native
native: 
      ocamlbuild -use-ocamlfind -package qcheck e2.native
byte: 
      ocamlbuild -use-ocamlfind -package qcheck e2.byte
clean: 
      ocamlbuild -clean
