all: 
      ocamlbuild -use-ocamlfind -package qcheck lec.native
native: 
      ocamlbuild -use-ocamlfind -package qcheck lec.native
byte: 
      ocamlbuild -use-ocamlfind -package qcheck lec.byte
clean: 
      ocamlbuild -clean
